/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.footer-icon[_ngcontent-%COMP%] {\r\n  font-size: xx-large;\r\n}\r\n\r\n.image-viewer-tooltip[_ngcontent-%COMP%] {\r\n  position: relative;\r\n  display: inline-block;\r\n  z-index: 1000;\r\n}\r\n\r\n.image-viewer-tooltip[_ngcontent-%COMP%]   .tooltiptext[_ngcontent-%COMP%] {\r\n  visibility: hidden;\r\n  width: 120px;\r\n  background-color: #555;\r\n  color: #fff;\r\n  text-align: center;\r\n  border-radius: 6px;\r\n  padding: 5px 0;\r\n  position: absolute;\r\n  z-index: 1;\r\n  bottom: 125%;\r\n  left: 40%;\r\n  margin-left: -60px;\r\n  opacity: 0;\r\n  transition: opacity 0.3s;\r\n}\r\n\r\n.image-viewer-tooltip[_ngcontent-%COMP%]   .tooltiptext[_ngcontent-%COMP%]::after {\r\n  content: "";\r\n  position: absolute;\r\n  top: 100%;\r\n  left: 50%;\r\n  margin-left: -5px;\r\n  border-width: 5px;\r\n  border-style: solid;\r\n  border-color: #555 transparent transparent transparent;\r\n}\r\n\r\n.image-viewer-tooltip[_ngcontent-%COMP%]:hover   .tooltiptext[_ngcontent-%COMP%] {\r\n  visibility: visible;\r\n  opacity: 1;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGF0YS9zcmsvbmcyLWltYWdlLXZpZXdlci9zcmMvaW1hZ2Utdmlld2VyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0RhdGEvc3JrL25nMi1pbWFnZS12aWV3ZXIvc3JjL2ltYWdlLXZpZXdlci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
